- op: add
  path: /spec/template/spec/serviceAccountName
  value: %SERVICE_ACCOUNT_NAME%
- op: add
  path: /spec/template/spec/initContainers/-
  value:
    name: pv-mount-permissions
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
      - chown -v -R 999:999 /mount;
    volumeMounts:
      - mountPath: /mount/data
        name: sonarqube
        subPath: data
      - mountPath: /mount/tmp
        name: sonarqube
        subPath: tmp
      - mountPath: /mount/downloads
        name: sonarqube
        subPath: downloads
      - mountPath: /mount/plugins
        name: sonarqube
        subPath: plugins
      - mountPath: /mount/temp
        name: sonarqube
        subPath: temp
      - mountPath: /mount/logs
        name: sonarqube
        subPath: logs
