{{ if .Values.createJob -}}
apiVersion: batch/v1
kind: Job
metadata:
    name: {{ include "jenkins-config.fullname" . }}
spec:
    template:
        spec:
            serviceAccountName: jenkins
            initContainers:
              - name: wait-for-jenkins
                image: garagecatalyst/ibm-garage-cli-tools:latest
                imagePullPolicy: Always
                command: ["sh", "-c", "until curl -Isf ${JENKINS_URL}; do echo '>>> waiting for Jenkins'; sleep 300; done; echo '>>> Jenkins has started'"]
                env:
                - name: JENKINS_URL
                  value: {{ printf "%s/login" (include "jenkins-config.url" .) }}
            containers:
                - name: jenkins-config
                  image: garagecatalyst/node11:latest
                  imagePullPolicy: Always
                  command: ["bash", "-c", "npm i -g @garage-catalyst/ibm-garage-cloud-cli && ~/.npm-packages/bin/igc jenkins-auth --inCluster"]
                  env:
                      - name: JENKINS_HOST
                        value: {{ .Values.jenkins.host | quote }}
                      - name: JENKINS_URL
                        value: {{ include "jenkins-config.url" . }}
                      - name: JENKINS_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: jenkins
                                key: jenkins-admin-user
                      - name: JENKINS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: jenkins
                                key: jenkins-admin-password
            restartPolicy: Never
    backoffLimit: 4
{{ end -}}
