nameOverride: artifactory

artifactory:
  image:
    repository: docker.bintray.io/jfrog/artifactory-oss
  accessAdmin:
    password: admin
  persistence:
    enabled: true
    size: 5Gi

ingress:
  enabled: true

postgresql:
  enabled: false

nginx:
  enabled: false

serviceAccount:
  create: false
  name: artifactory-artifactory
